name: e_shop
description: Flutter eCommerce App using Firebase Firestore
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.0.0
  cupertino_icons: ^1.0.2
  cloud_firestore: ^1.0.0
  firebase_auth: ^1.0.0
  shared_preferences: ^0.5.6+1
  image_picker: ^0.6.3+1
  firebase_storage: ^8.0.0
  flutter_staggered_grid_view: ^0.3.0
  provider: ^4.0.4
  path_provider: ^2.0.1
  image: ^3.0.1
  fluttertoast: ^8.0.6
  intl:
  location: ^4.1.1
  weather_icons: ^2.0.2
  connectivity: ^3.0.3


#  cupertino_icons: ^0.1.2
#  cloud_firestore: ^0.13.2+1
#  firebase_auth: ^0.15.4
#  shared_preferences: ^0.5.6+1
#  fluttertoast: ^3.1.3
#  image_picker: ^0.6.3+1
#  firebase_storage: ^3.1.1
#  flutter_staggered_grid_view: ^0.3.0
#  provider: ^4.0.4
#  path_provider: ^0.5.0+1
#  image: ^2.0.7
#  intl:



dev_dependencies:
  flutter_test:
    sdk: flutter

  wemapgl:
    path: ./WeMap-Flutter-SDK-master


flutter:
  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf

  assets:
    - images/welcome.png
    - images/login.png
    - images/admin.png
    - images/cash.png
    - assets/symbols/custom-icon.png
    - assets/symbols/origin.png
    - assets/symbols/destination.png
    - assets/symbols/2.0x/custom-icon.png
    - assets/symbols/2.0x/origin.png
    - assets/symbols/2.0x/destination.png
    - assets/symbols/3.0x/custom-icon.png
    - assets/symbols/3.0x/origin.png
    - assets/symbols/3.0x/destination.png
    - assets/geojson/ne_10m_ports.geojson
    - assets/geojson/line-samples.geojson
    - assets/geojson/polygon-samples.geojson



